### ISSUE TITLE
Update / delete combination gives wrong result (diff method)

### ISSUE THREAD

**Issue by ddhaeyere** [CADbloke/google-diff-match-patch#107]
Take two text files to compare.

The first one being the original, the second one the file to compare with the first one.
suppose the first file has 20 lines of text

In the second file: remove line 10 and edit the new line 10 (which was before line 11).

The result is that you only see an update. The delete is not mentioned.

It is not clear to state which line (original 10th line or original 11th line) is changed and which one is deleted. But since there is one line less in the new file, there should be an indication of a delete.

**Comment by CADbloke** [comment]
Hiya, I cloned this from Google Code so it wouldn't be lost in the mists of time. I'm not the owner.

Also, 
- this has like a billion different language versions and you didn't mention which one. 
- No code,
- no text files.

https://www.google.com.au/search?safe=active&q=how+to+good+bug+report

Please, I mean no offense but I can't do anything with that information. Also, unless it's the C# version, I probably can't help you because that's the only one I use.
